### ISSUE TITLE
v1.17 failed on WSL Ubuntu 

### ISSUE THREAD

**Issue by hcchengithub** [hcchengithub/peforth#1]
### When without virtualenv:
    hcchen5600@WKS-4AEN0404:~$ python -m peforth
    Traceback (most recent call last):
      ...snip...   
      File "/home/hcchen5600/.local/lib/python3.6/site-packages/peforth/__init__.py", line 67, in <module>
        exec(readTextFile(path + "version.txt"),{},locals())
      File "/home/hcchen5600/.local/lib/python3.6/site-packages/peforth/__init__.py", line 35, in readTextFile
        f = open(pathname,'r',encoding='utf-8')
    FileNotFoundError: [Errno 2] No such file or directory: 'something wrong peforth path not foundversion.txt'    

### When with virtualenv:
    (playground) hcchen5600@WKS-4AEN0404:~$ python -m peforth
    Traceback (most recent call last):
      ...snip...  
      File "/home/hcchen5600/playground/lib/python3.6/site-packages/peforth/__init__.py", line 57, in <module>
        for p in (pp for pp in site.getsitepackages() if pp.endswith("site-packages")):
    AttributeError: module 'site' has no attribute 'getsitepackages'

**Comment by hcchengithub** [comment]
Root cause identified, Fix confirmed

1. `pip show peforth` to find the site-packages location which on my computer is 
    /home/hcchen5600/playground/lib/python3.6/site-packages 
2. edit <location>/peforth/__init__py 
3. modify `site.getsitepackages()` to `sys.path` , that's all.

Next release will include this solution. meanwhile please correct it with the above modification.
