### ISSUE TITLE
how does it work on python 3.7?

### ISSUE THREAD

**Issue by hcchengithub** [hcchengithub/peforth#3]
鄧淵元:昨天升級了Miniconda，結果3.7版執行 peforth 1.23 版會有問題。
看來還是直接用Azure的版本比較單純。

hcchen5600: python 3.7 沒試過，我試試看？
您覺得是 python 3.7 還是 miniconda 的問題？

鄧淵元:應該是python3.7

hcchen5600: 那我看看 . . . . . 
一打開 WSL ubuntu 馬上發現我完全忘了先前在上面玩過甚麼了 

鄧淵元: 我也是，哈哈

hcchen5600: 用 lsb_release -a 命令查出這個 Ubuntu 是 18.04 
然後想看它的 python 是哪版怎麼查? 我記得這個會很茫然，因為多個 python 可以並存。
喔，是 3.6.5 。我突然覺得還是不要太急好了，以免白花功夫。你看的問題有截圖嗎？

鄧淵元: 也是。改天降回去 3.65

hcchen5600:
問題一、python 3.7 適合在 ubuntu 18.04 上跑嗎？
問題二、python 3.7 有何必要？3.6 不好嗎？
哈! 您也想要降回去，先留個錯誤的截圖吧

鄧淵元: 機器在家裡。我會去截圖

hcchen5600: 好! 很有幫助，留個紀錄就好.

**Comment by hcchengithub** [comment]
我裝好了 python 3.7 on WSL ubuntu 18.04 
本來的 python 是 3.6.5 可能是我先前裝上的，我記得 ubuntu built-in 的是 python 2.7.
結果裝好 3.7 之後本來的 3.6.5 變成了 3.6.8 應該是過程中的 upgrade 步驟之功勞。
裝好了 python 3.7 要試 peforth 又發現沒有 pip, 照畫面指示裝了 pip3 又是 python 3.6 的而非 3.7 的，所以 pip install peforth 是給 python 3.6 的 (跑進 /home/hcchen/.local/lib/python3.6/site-packages/peforth/). 
至於 python 3.7 的 pip 該如何安裝上 WSL Ubuntu 18.04? 不知道了。

**Comment by hcchengithub** [comment]
鄧淵元:
我把錯誤的訊息寄到你的gmail信箱。

鄧淵元:
收一下。


On Thu, Jul 4, 2019 at 10:51 PM 鄧淵元 <deng.daniel@forth.org.tw> wrote:
請參考

Daniel 

Adapting to protocol v5.1 for kernel ed8c676e-2ddb-47d3-a211-c17a43fac00d
[W 22:47:00.519 NotebookApp] 404 GET /static/components/codemirror/mode/peforth/peforth.js?v=20190704224443 (127.0.0.1) 12.12ms referer=http://localhost:8888/notebooks/Untitled1.ipynb?kernel_name=peforth
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/home/daniel/miniconda/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 272, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/home/daniel/miniconda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/home/daniel/miniconda/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/daniel/miniconda/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 542, in execute_request
    user_expressions, allow_stdin,
  File "./miniconda/lib/python3.7/site-packages/peforth/peforthkernel.py", line 20, in do_execute
    code_result = peforth.vm.pop()[0]
  File "/home/daniel/miniconda/lib/python3.7/site-packages/peforth/projectk.py", line 565, in pop
    return stack.pop();
IndexError: pop from empty list

**Comment by hcchengithub** [comment]
從上面 error log 看來("404 GET . . . .")，是在跑一個 jupyter notebook 的時候出的錯！
而且還有個 "peforth.js" 的字樣也很奇怪。需要詳細的複製步驟。
